/* Engineer(s): Ezzeddeen Gazali and Tyler Starr
 * Create Date: 05/26/2018
 */
#include "servo.h"

/*
 * Function that initialize the PWM on Timer A2, utilizes port P6.6
 * Inputs       NONE
 * Return       NONE
 */
void PWM_init(void)
{
    //configure clock systems, SMCLK to 3MHz
    CS -> KEY = CS_KEY_VAL;
    CS -> CTL0 = 0;
    CS -> CTL0 |= CS_CTL0_DCORSEL_1;
    CS -> CTL1 |= CS_CTL1_SELS__DCOCLK;
    CS -> KEY = 0;

    //configure GPIO
    P6 -> SEL0 |= BIT6;
    P6 -> DIR  |= BIT6;

    //Select SMCLK as the source for TIMERA2 and use UP mode
    TIMER_A2-> CTL =  TIMER_A_CTL_SSEL__SMCLK |
                      TIMER_A_CTL_MC__UP      |
                      TIMER_A_CTL_CLR;
    //select output mode 7
    TIMER_A2->CCTL[3] = TIMER_A_CCTLN_OUTMOD_7;

    //set CCR0 and CCR3 values
    TIMER_A2->CCR[0] = PERIOD_COUNT;
    TIMER_A2->CCR[3] = 1500;
    return;
}

/*
 * Function that adjusts the PWM signal generated by Timer A2 based on the desired
 * servo angle
 * Inputs       uint8_t degree = angle to rotate servo to, 00-18, actual angle multiplied by 10
 * Return       NONE
 */
void servo_angle(uint8_t degree)
{
    if(degree <= 18)                                //only accept angles between 0 and 18
    {
        uint32_t timeOnCount = 1500 + degree*310;  //formula to determine "ON" time
        TIMER_A2->CCR[0] = PERIOD_COUNT;
        TIMER_A2->CCR[3] = timeOnCount;
    }
    return;
}
